# Generated by Django 5.2.5 on 2025-08-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('language', models.CharField(max_length=64)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banner_image_desktop', models.ImageField(blank=True, null=True, upload_to='live_courses/banner_desktop/')),
                ('banner_image_mobile', models.ImageField(blank=True, null=True, upload_to='live_courses/banner_mobile/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('about', models.TextField(blank=True)),
                ('target_exam', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=220)),
                ('enable_auto_recording', models.BooleanField(default=False)),
                ('repeat_weekly', models.BooleanField(default=False)),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('is_free', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='live_class.liveclasscourse')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
    ]
