# Generated by Django 5.2.5 on 2025-08-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclasssession',
            name='repeat_weekly',
        ),
    ]
