# Generated by Django 5.2.5 on 2025-09-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0002_remove_liveclasssession_repeat_weekly'),
        ('video_courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclasscourse',
            name='target_exam',
        ),
        migrations.AddField(
            model_name='liveclasscourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_class_courses', to='video_courses.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='class_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
