# Generated by Django 5.2.7 on 2025-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0003_remove_liveclasscourse_target_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclasscourse',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Check if this is a free course'),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Override course pricing for this session'),
        ),
    ]
