# Generated by Django 5.2.5 on 2025-09-06 10:21

import adminpanel.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='EduGorilla Community Pvt. Ltd.', max_length=200)),
                ('heading', models.CharField(default='About EduGorilla', max_length=200)),
                ('description', models.TextField(default="India's fastest-growing one-stop exam prep platform")),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', upload_to='about/')),
                ('address', models.TextField(default='6th Floor, Intech Capital, Vibhuti Khand, Gomti Nagar, Lucknow - 226010, India')),
                ('email', models.EmailField(default='info@edugorilla.com', max_length=254)),
                ('phone', models.CharField(default='0522-3514751', max_length=50)),
                ('phone_hours', models.CharField(default='(10 AM to 7 PM)', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/edugorilla')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/edugorilla')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/edugorilla')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/edugorilla')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/edugorilla')),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3559.179356267426!2d81.01998567588361!3d26.868361676681647!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399be3b383c2f1d7%3A0x45a6a4568b63d9ed!2sIntech%20Capital%2C%20Vibhuti%20Khand%2C%20Gomti%20Nagar%2C%20Lucknow%2C%20Uttar%20Pradesh%20226010!5e0!3m2!1sen!2sin!4v1711914801650!5m2!1sen!2sin', help_text='Google Maps embed URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=adminpanel.models.banner_upload_path)),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when banner is clicked')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main CTA text', max_length=200)),
                ('button_text', models.CharField(help_text='Button text', max_length=100)),
                ('button_link', models.URLField(blank=True, help_text='Optional button link')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='FooterLegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Legal link title', max_length=100)),
                ('url', models.CharField(help_text='Legal link URL', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Footer Legal Link',
                'verbose_name_plural': 'Footer Legal Links',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About'), ('help', 'Help'), ('student', 'Student'), ('business', 'Business')], help_text='Footer section', max_length=20)),
                ('title', models.CharField(help_text='Link title', max_length=100)),
                ('url', models.CharField(help_text='Link URL (use # for placeholder)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order within section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['section', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Footer logo image', null=True, upload_to='footer/')),
                ('email', models.EmailField(default='testseries@edugorilla.com', help_text='Contact email', max_length=254)),
                ('copyright_text', models.CharField(default='Copyright © 2025 EduGorilla Community Pvt. Ltd.', max_length=200)),
                ('google_play_url', models.URLField(blank=True, default='https://play.google.com/store/apps', help_text='Google Play Store URL')),
                ('app_store_url', models.URLField(blank=True, default='https://apps.apple.com/app', help_text='Apple App Store URL')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/edugorilla')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/edugorilla')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/edugorilla')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/edugorilla')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/edugorilla')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/edugorilla')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Website logo', null=True, upload_to='navbar/')),
                ('contact_number', models.CharField(default='7905817391', help_text='Contact phone number', max_length=20)),
                ('contact_hours', models.CharField(default='(10 AM to 7 PM)', help_text='Contact hours', max_length=50)),
                ('search_placeholder', models.CharField(default='Search courses', help_text='Search box placeholder text', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa fa-video-camera', help_text='FontAwesome icon class', max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default SMTP', max_length=100)),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP Backend'), ('django.core.mail.backends.console.EmailBackend', 'Console Backend (Development)')], default='django.core.mail.backends.smtp.EmailBackend', max_length=200)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=200)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('email_host_user', models.EmailField(help_text='Email address for authentication', max_length=254)),
                ('email_host_password', models.CharField(help_text='Email password or app password', max_length=200)),
                ('default_from_email', models.EmailField(help_text='Default sender email address', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon (e.g., 👥)', max_length=10)),
                ('number', models.CharField(help_text='Statistic number (e.g., 4 Crore+)', max_length=50)),
                ('label', models.CharField(help_text='Label text (e.g., Users)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa fa-user-circle', help_text='FontAwesome icon class', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='adminpanel.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='adminpanel.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
