# Generated by Django 5.2.5 on 2025-09-21 09:05

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statcard',
            name='icon_color',
            field=models.CharField(default='#007bff', help_text='Hex color code for Font Awesome icons (e.g., #007bff)', max_length=7),
        ),
        migrations.AddField(
            model_name='statcard',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload custom icon image (.png, .jpg, .svg)', null=True, upload_to=adminpanel.models.stat_icon_upload_path),
        ),
        migrations.AddField(
            model_name='statcard',
            name='icon_type',
            field=models.CharField(choices=[('font_awesome', 'Font Awesome Icon'), ('image', 'Custom Image')], default='font_awesome', help_text='Choose between Font Awesome icon or custom image', max_length=20),
        ),
        migrations.AlterField(
            model_name='statcard',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon name (e.g., users, graduation-cap)', max_length=50, null=True),
        ),
    ]
