# Generated by Django 5.2.5 on 2025-08-21 17:08

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_bannersection_statisticitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=adminpanel.models.banner_upload_path)),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when banner is clicked')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BannerSection',
        ),
        migrations.DeleteModel(
            name='StatisticItem',
        ),
    ]
