# Generated by Django 5.2.5 on 2025-08-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_ctasection_statcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='EduGorilla Community Pvt. Ltd.', max_length=200)),
                ('heading', models.CharField(default='About EduGorilla', max_length=200)),
                ('description', models.TextField(default="India's fastest-growing one-stop exam prep platform")),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', upload_to='about/')),
                ('address', models.TextField(default='6th Floor, Intech Capital, Vibhuti Khand, Gomti Nagar, Lucknow - 226010, India')),
                ('email', models.EmailField(default='info@edugorilla.com', max_length=254)),
                ('phone', models.CharField(default='0522-3514751', max_length=50)),
                ('phone_hours', models.CharField(default='(10 AM to 7 PM)', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/edugorilla')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/edugorilla')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/edugorilla')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/edugorilla')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/edugorilla')),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3559.179356267426!2d81.01998567588361!3d26.868361676681647!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399be3b383c2f1d7%3A0x45a6a4568b63d9ed!2sIntech%20Capital%2C%20Vibhuti%20Khand%2C%20Gomti%20Nagar%2C%20Lucknow%2C%20Uttar%20Pradesh%20226010!5e0!3m2!1sen!2sin!4v1711914801650!5m2!1sen!2sin', help_text='Google Maps embed URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa fa-video-camera', help_text='FontAwesome icon class', max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa fa-user-circle', help_text='FontAwesome icon class', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
