# Generated by Django 5.2.5 on 2025-08-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_aboutussection_serviceitem_whychooseusitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Website logo', null=True, upload_to='navbar/')),
                ('contact_number', models.CharField(default='7905817391', help_text='Contact phone number', max_length=20)),
                ('contact_hours', models.CharField(default='(10 AM to 7 PM)', help_text='Contact hours', max_length=50)),
                ('search_placeholder', models.CharField(default='Search courses', help_text='Search box placeholder text', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
    ]
