# Generated by Django 5.2.5 on 2025-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_navbarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Legal link title', max_length=100)),
                ('url', models.CharField(help_text='Legal link URL', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Footer Legal Link',
                'verbose_name_plural': 'Footer Legal Links',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About'), ('help', 'Help'), ('student', 'Student'), ('business', 'Business')], help_text='Footer section', max_length=20)),
                ('title', models.CharField(help_text='Link title', max_length=100)),
                ('url', models.CharField(help_text='Link URL (use # for placeholder)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order within section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['section', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Footer logo image', null=True, upload_to='footer/')),
                ('email', models.EmailField(default='testseries@edugorilla.com', help_text='Contact email', max_length=254)),
                ('copyright_text', models.CharField(default='Copyright © 2025 EduGorilla Community Pvt. Ltd.', max_length=200)),
                ('google_play_url', models.URLField(blank=True, default='https://play.google.com/store/apps', help_text='Google Play Store URL')),
                ('app_store_url', models.URLField(blank=True, default='https://apps.apple.com/app', help_text='Apple App Store URL')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/edugorilla')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/edugorilla')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/edugorilla')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/edugorilla')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/edugorilla')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me/edugorilla')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
