# Generated by Django 5.2.5 on 2025-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_footerlegallink_footerlink_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default SMTP', max_length=100)),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP Backend'), ('django.core.mail.backends.console.EmailBackend', 'Console Backend (Development)')], default='django.core.mail.backends.smtp.EmailBackend', max_length=200)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=200)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('email_host_user', models.EmailField(help_text='Email address for authentication', max_length=254)),
                ('email_host_password', models.CharField(help_text='Email password or app password', max_length=200)),
                ('default_from_email', models.EmailField(help_text='Default sender email address', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
