# Generated by Django 5.2.7 on 2025-10-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_statcard_icon_color_statcard_icon_image_and_more'),
        ('adminpanel', '0009_smtpconfiguration'),
    ]

    operations = [
    ]
