# Generated by Django 5.2.7 on 2025-10-14 03:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_merge_20251012_0011'),
        ('elibrary', '0002_remove_elibraryitem_category_and_more'),
        ('live_class', '0003_remove_liveclasscourse_target_exam_and_more'),
        ('testseries', '0003_testattemptlog_testreview_and_more'),
        ('video_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the bundle')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for cards', max_length=300)),
                ('bundle_type', models.CharField(choices=[('mixed', 'Mixed Bundle'), ('video_only', 'Video Courses Only'), ('live_only', 'Live Classes Only'), ('test_only', 'Test Series Only'), ('elibrary_only', 'E-Library Only')], default='mixed', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='bundles/thumbnails/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='bundles/banners/')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Total original price of all included products', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bundle_price', models.DecimalField(decimal_places=2, help_text='Special bundle price (should be less than original)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('features', models.TextField(blank=True, help_text='One feature per line, will be displayed as bullet points')),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='Number of days the bundle is valid after purchase')),
                ('start_date', models.DateField(blank=True, help_text='Bundle availability start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Bundle availability end date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority')),
                ('max_enrollments', models.PositiveIntegerField(blank=True, help_text='Maximum number of students who can purchase (leave empty for unlimited)', null=True)),
                ('current_enrollments', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='video_courses.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bundles', to=settings.AUTH_USER_MODEL)),
                ('elibrary_courses', models.ManyToManyField(blank=True, help_text='Select e-library courses to include', related_name='bundles', to='elibrary.elibrarycourse')),
                ('live_classes', models.ManyToManyField(blank=True, help_text='Select live class courses to include', related_name='bundles', to='live_class.liveclasscourse')),
                ('test_series', models.ManyToManyField(blank=True, help_text='Select test series to include', related_name='bundles', to='testseries.testseries')),
                ('video_courses', models.ManyToManyField(blank=True, help_text='Select video courses to include', related_name='bundles', to='video_courses.videocourse')),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('total_access_count', models.PositiveIntegerField(default=0)),
                ('refund_requested_at', models.DateTimeField(blank=True, null=True)),
                ('refund_approved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_enrollments', to=settings.AUTH_USER_MODEL)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='adminpanel.productbundle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Overall rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('value_for_money', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('content_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('review_title', models.CharField(blank=True, max_length=200)),
                ('review_text', models.TextField(blank=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='adminpanel.bundleenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_reviews', to=settings.AUTH_USER_MODEL)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adminpanel.productbundle')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bundle')},
            },
        ),
        migrations.AddIndex(
            model_name='bundleenrollment',
            index=models.Index(fields=['user', 'payment_status'], name='adminpanel__user_id_761349_idx'),
        ),
        migrations.AddIndex(
            model_name='bundleenrollment',
            index=models.Index(fields=['bundle', 'payment_status'], name='adminpanel__bundle__8a51fd_idx'),
        ),
        migrations.AddIndex(
            model_name='bundleenrollment',
            index=models.Index(fields=['payment_id'], name='adminpanel__payment_935e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bundleenrollment',
            unique_together={('user', 'bundle')},
        ),
    ]
