# Generated by Django 5.2.7 on 2025-10-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_productbundle_bundleenrollment_bundlereview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlereview',
            name='enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='bundlereview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bundlereview',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='bundlereview',
            name='user',
        ),
        migrations.DeleteModel(
            name='BundleEnrollment',
        ),
        migrations.DeleteModel(
            name='BundleReview',
        ),
    ]
