# Generated by Django 5.2.7 on 2025-10-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_remove_bundlereview_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsettings',
            name='contact_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone Call')], default='whatsapp', help_text='Contact method type', max_length=10),
        ),
        migrations.AddField(
            model_name='navbarsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website favicon (16x16 or 32x32 px)', null=True, upload_to='navbar/favicon/'),
        ),
    ]
