# Generated by Django 5.2.7 on 2025-11-04 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_navbarsettings_contact_type_navbarsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundle',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Check if this bundle is completely free'),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='bundle_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Special bundle price (should be less than original)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total original price of all included products', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
