# Generated by Django 5.2.7 on 2025-11-14 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_productbundle_is_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Developer profile image. Recommended: 300x300px, max 1MB', null=True, upload_to='developer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('greeting_text', models.CharField(default="Greetings! I'm", help_text='Greeting message before developer name', max_length=100)),
                ('developer_name', models.CharField(help_text='Full name of the developer', max_length=200)),
                ('tagline', models.TextField(help_text='Brief description/tagline about the developer (max 500 characters)', max_length=500)),
                ('message_title', models.CharField(default='I design professional websites!', help_text='Bold message title', max_length=200)),
                ('message_body', models.TextField(help_text='Main message body text')),
                ('email', models.EmailField(help_text='Developer email address', max_length=254)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number with country code (e.g., 917905817391)', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn profile URL', null=True)),
                ('linkedin_display_text', models.CharField(default='Rudra Narayan Tiwari', help_text='Text to display for LinkedIn link', max_length=200)),
                ('footer_message', models.CharField(default='🚀 Looking forward to working with all of you!', help_text='Footer message displayed at bottom of popup', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide the popup on website')),
                ('delay_seconds', models.PositiveIntegerField(default=1, help_text='Delay in seconds before showing popup (default: 1 second)')),
                ('show_once_per_session', models.BooleanField(default=True, help_text='Show popup only once per browser session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Popup',
                'verbose_name_plural': 'Developer Popup Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
