# Generated by Django 5.2.7 on 2025-11-14 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_developerpopup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWAInstallPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Name of your app (e.g., EduTrellis)', max_length=100)),
                ('app_logo', models.ImageField(help_text='App logo/icon. Recommended: 512x512px, max 1MB', upload_to='pwa_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])])),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable PWA install prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PWA Install Prompt',
                'verbose_name_plural': 'PWA Install Prompt Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
