# Generated by Django 5.2.7 on 2025-11-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_pwainstallprompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PWAInstallPrompt',
        ),
    ]
