# Generated by Django 5.2.7 on 2025-11-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_customnotificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomNotificationLog',
        ),
    ]
