# Generated by Django 5.2.7 on 2025-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_delete_customnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('body', models.TextField(help_text='Notification message/content')),
                ('link', models.URLField(blank=True, help_text='Optional link (leave empty if not needed)', max_length=500, null=True)),
                ('scheduled_time', models.DateTimeField(help_text='When to show this notification')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-scheduled_time', '-created_at'],
            },
        ),
    ]
