# Generated by Django 5.2.12 on 2026-09-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Razorpay', max_length=100)),
                ('key_id', models.CharField(help_text='Razorpay Key ID (for example, rzp_test_...)', max_length=100)),
                ('key_secret', models.CharField(help_text='Razorpay Key Secret', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Razorpay Configuration',
                'verbose_name_plural': 'Razorpay Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
