# Generated by Django 5.2.12 on 2026-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_dropboxconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctasection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional background image (recommended 1920x600px)', null=True, upload_to='cta/'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='button_color',
            field=models.CharField(default='#D4AF37', help_text='Hex color code for the CTA button (e.g., #D4AF37)', max_length=7),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description or tagline for the call-to-action', max_length=300),
        ),
    ]
