# Generated by Django 5.2.12 on 2026-09-18 19:56

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_ctasection_background_image_ctasection_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional mobile-only banner. Recommended size: 750x400px. Falls back to the desktop image if left blank.', null=True, upload_to=adminpanel.models.banner_upload_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1920x800px', upload_to=adminpanel.models.banner_upload_path),
        ),
    ]
