# Generated by Django 5.2.12 on 2026-09-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_image', models.ImageField(blank=True, help_text='Side image for the login page. Recommended size: 1000x1200px. Falls back to the default image if left blank.', null=True, upload_to='auth_pages/')),
                ('signup_image', models.ImageField(blank=True, help_text='Side image for the signup page. Recommended size: 1000x1200px. Falls back to the default image if left blank.', null=True, upload_to='auth_pages/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login/Signup Page Settings',
                'verbose_name_plural': 'Login/Signup Page Settings',
            },
        ),
    ]
