# Generated by Django 5.2.12 on 2026-09-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_authpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Used in the page URL, e.g. privacy-policy', max_length=150, unique=True)),
                ('content', models.TextField(help_text='Page content. Basic HTML tags are allowed.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extra Page',
                'verbose_name_plural': 'Extra Pages',
                'ordering': ['title'],
            },
        ),
    ]
