# Generated by Django 5.2.7 on 2025-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='is_free',
            field=models.BooleanField(default=False, help_text="If checked, course is free. Otherwise, it's paid."),
        ),
    ]
