# Generated by Django 6.0 on 2026-03-04 03:52

import video_courses.dropbox_storage
import video_courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0002_videocourse_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='file',
            field=models.FileField(storage=video_courses.dropbox_storage.DropboxStorage(), upload_to=video_courses.models.course_video_upload),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, storage=video_courses.dropbox_storage.DropboxStorage(), upload_to='video_courses/video_thumbs/'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='instructor_avatar',
            field=models.ImageField(blank=True, null=True, storage=video_courses.dropbox_storage.DropboxStorage(), upload_to='video_courses/instructors/'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=video_courses.dropbox_storage.DropboxStorage(), upload_to=video_courses.models.course_thumb_upload),
        ),
    ]
