# Generated by Django 5.2.12 on 2026-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_courses', '0003_alter_coursevideo_file_alter_coursevideo_thumb_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='graduation-cap', help_text="Font Awesome icon name, without the 'fa-' prefix (e.g., 'shield-alt', 'stethoscope').", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_color',
            field=models.CharField(default='#667eea', help_text='Hex color code for the category icon (e.g., #667eea).', max_length=7),
        ),
    ]
