# Generated by Django 5.2.5 on 2025-09-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0001_initial'),
        ('video_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseries',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_series', to='video_courses.category'),
        ),
        migrations.DeleteModel(
            name='TestSeriesCategory',
        ),
    ]
