# Generated by Django 5.2.7 on 2025-10-12 11:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0002_alter_testseries_category_delete_testseriescategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttemptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('started', 'Test Started'), ('question_viewed', 'Question Viewed'), ('answer_selected', 'Answer Selected'), ('answer_changed', 'Answer Changed'), ('marked_review', 'Marked for Review'), ('unmarked_review', 'Unmarked Review'), ('tab_switch', 'Tab Switched'), ('window_blur', 'Window Lost Focus'), ('submitted', 'Test Submitted'), ('auto_submitted', 'Auto Submitted (Time Up)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('difficulty_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['question__order']},
        ),
        migrations.AddField(
            model_name='question',
            name='solution_video_url',
            field=models.URLField(blank=True, help_text='YouTube or video URL', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='first_visited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='difficulty_wise_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='remaining_time',
            field=models.PositiveIntegerField(default=0, help_text='Remaining time in seconds'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testseries',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testseries',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='testseries.testattempt'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_visited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='testseries.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='question_wise_time',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='subject_wise_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testseries.test'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='testseries__attempt_787285_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question', 'is_correct'], name='testseries__questio_658945_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', 'status'], name='testseries__user_id_08458f_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'submitted_at'], name='testseries__test_id_7bc11c_idx'),
        ),
        migrations.AddField(
            model_name='testattemptlog',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='testseries.testattempt'),
        ),
        migrations.AddField(
            model_name='testattemptlog',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testseries.question'),
        ),
        migrations.AddField(
            model_name='testreview',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='testseries.testattempt'),
        ),
        migrations.AddField(
            model_name='testreview',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='testseries.test'),
        ),
        migrations.AddField(
            model_name='testreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='testattemptlog',
            index=models.Index(fields=['attempt', 'action'], name='testseries__attempt_142f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattemptlog',
            index=models.Index(fields=['created_at'], name='testseries__created_bb094f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testreview',
            unique_together={('user', 'test')},
        ),
    ]
