# Generated by Django 5.2.7 on 2025-10-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alternative_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_username',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1),
        ),
    ]
