# Generated by Django 5.2.7 on 2025-11-03 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_type', models.CharField(max_length=50)),
                ('access_granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Course Access',
                'verbose_name_plural': 'User Course Access Records',
                'ordering': ['-access_granted_at'],
                'unique_together': {('user', 'course_id', 'course_type')},
            },
        ),
    ]
