# Generated by Django 5.2.7 on 2025-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('free_live_class', 'Free Live Class'), ('free_session', 'Free Session'), ('course_update', 'Course Update'), ('announcement', 'Announcement'), ('offer', 'Special Offer'), ('reminder', 'Reminder')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='base_notifi_related_7d1ec2_idx'),
        ),
    ]
