# Generated by Django 5.2.7 on 2025-11-16 17:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_notification_options_notification_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notification_type', models.CharField(max_length=50)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Send to all users'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target_group',
            field=models.CharField(blank=True, help_text='Target user group', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('free_live_class', 'Free Live Class'), ('free_session', 'Free Session'), ('course_update', 'Course Update'), ('announcement', 'Announcement'), ('offer', 'Special Offer'), ('reminder', 'Reminder'), ('system', 'System Notice'), ('custom', 'Custom Message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'High'), (2, 'Urgent')], default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_global'], name='base_notifi_is_glob_227a1d_idx'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
