# Generated by Django 5.2.5 on 2025-09-06 10:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
        ('video_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elibraryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='elibraryitem',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='elibrarydownload',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ELibraryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for card view', max_length=300)),
                ('instructor', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='elibrary/courses/covers/')),
                ('preview_pdf', models.FileField(blank=True, null=True, upload_to='elibrary/courses/previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('total_pdfs', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='Approximate total pages')),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('language', models.CharField(default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elibrary_courses', to='video_courses.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ELibraryEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elibrary.elibrarycourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ELibraryPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='elibrary/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('chapter_number', models.PositiveIntegerField(default=1, help_text='Chapter or section number')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within chapter')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('is_preview', models.BooleanField(default=False, help_text='Available as free preview')),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='elibrary.elibrarycourse')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chapter_number', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='elibrarydownload',
            name='pdf',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='elibrary.elibrarypdf'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ELibraryCategory',
        ),
        migrations.RemoveField(
            model_name='elibrarydownload',
            name='item',
        ),
        migrations.DeleteModel(
            name='ELibraryItem',
        ),
    ]
