# Generated by Django 5.2.7 on 2025-11-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_remove_elibraryitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elibrarycourse',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Make this course free for all users'),
        ),
    ]
