# Generated by Django 5.2.12 on 2026-08-29 11:12

import django.core.validators
import video_courses.dropbox_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0003_elibrarycourse_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrarycourse',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=video_courses.dropbox_storage.DropboxStorage(), upload_to='elibrary/courses/covers/'),
        ),
        migrations.AlterField(
            model_name='elibrarycourse',
            name='preview_pdf',
            field=models.FileField(blank=True, null=True, storage=video_courses.dropbox_storage.DropboxStorage(), upload_to='elibrary/courses/previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='elibrarypdf',
            name='file',
            field=models.FileField(storage=video_courses.dropbox_storage.DropboxStorage(), upload_to='elibrary/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
